### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by grantjsg** [frappierer/ai-image-renamer#1]
Error ModuleNotFoundError: No module named 'requests' received.
<img width="1129" alt="Screenshot 2023-08-30 at 16 42 48" src="https://github.com/frappierer/ai-image-renamer/assets/143615290/ce9d62f0-99b7-43f6-b56d-b5a0f0570846">
Any tips?

**Comment by frappierer** [comment]
You need to install the python request library.

see https://www.agiratech.com/install-requests-library-in-python
